# Generated by Django 5.2.1 on 2025-05-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GreenhouseData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('metric', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('value', models.FloatField()),
                ('subcategory', models.CharField(max_length=255)),
            ],
        ),
    ]
