# Generated by Django 5.2.1 on 2025-05-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('subcategory', models.CharField(max_length=255)),
                ('metric', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('date_of_publication', models.DateField()),
                ('source', models.CharField(max_length=255)),
                ('link', models.URLField()),
            ],
        ),
    ]
