# Generated by Django 5.2.1 on 2025-05-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0002_energydata_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhousedata',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='greenhousedata',
            name='metric',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='greenhousedata',
            name='subcategory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
