# Generated by Django 5.2.1 on 2025-05-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0003_alter_greenhousedata_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiversityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('women_in_workforce', models.FloatField()),
                ('black_employees', models.FloatField()),
                ('latino_employees', models.FloatField()),
                ('asian_employees', models.FloatField()),
                ('multiracial_employees', models.FloatField()),
            ],
        ),
    ]
