# Generated by Django 5.2.1 on 2025-05-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0004_diversitydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energydata',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='greenhousedata',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
