# Generated by Django 5.2.1 on 2025-05-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=10)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField()),
                ('fixed_costs', models.FloatField(blank=True, null=True)),
                ('variable_costs', models.FloatField(blank=True, null=True)),
                ('units_sold', models.IntegerField(blank=True, null=True)),
                ('sales_revenue', models.FloatField(blank=True, null=True)),
                ('gross_margin', models.FloatField(blank=True, null=True)),
                ('operating_margin', models.FloatField(blank=True, null=True)),
                ('operating_profit', models.FloatField(blank=True, null=True)),
                ('net_profit', models.FloatField(blank=True, null=True)),
                ('equity', models.FloatField(blank=True, null=True)),
                ('liabilities', models.FloatField(blank=True, null=True)),
                ('roa', models.FloatField(blank=True, null=True)),
                ('roe', models.FloatField(blank=True, null=True)),
                ('current_ratio', models.FloatField(blank=True, null=True)),
                ('debt_ratio', models.FloatField(blank=True, null=True)),
                ('asset_turnover', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
