# Generated by Django 5.2.1 on 2025-05-31 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialdata',
            name='company_name',
        ),
    ]
