# Generated by Django 5.2.1 on 2025-05-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksdata',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
