# Generated by Django 5.2.1 on 2025-06-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0003_predict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocksdata',
            name='company_name',
        ),
    ]
